---
title: "S2_1 Time Series"
output:
  html_notebook: default
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

## Carga de librerias

```{r Carga de librerias}
library(ggplot2)
library(tsapp)
library(forecast)
library(scales)
library(stats)
library(TTR)
```

## Carga de datos

```{r Carga de datos}
#Carga de datos
Yt <- read.delim("./datasets/datatesisaereo.txt", header=T)
#ts para convertir a serie de tiempo
Yt <- ts(Yt, start = c(2000, 1), freq = 12 )
```
## Grafico de la seria

```{r Ploteo de Serie}
plot(Yt)
```

## Agrupacion de meses

```{r Agrupacion de meses}
cycle(Yt)
```

## Diagrama de Cajas

```{r Diagrama de cajas vertical}
boxplot(Yt ~ cycle(Yt), horizontal = FALSE, col = "YELLOW") ## ALT + 126
```

```{r Diagrama de cajas horizontal}
boxplot(Yt ~ cycle(Yt), horizontal = TRUE, col = "YELLOW") ## ALT + 126
```

##Descomposición de la serie de tipo multiplicativo
```{r Descomposición de la serie de tipo multiplicativo}
#Aplicamos la sentencia para un enf. de descomposicion
Yt.ts.desc <- decompose(Yt, type = "multiplicative")
Yt.ts.desc
```

```{r}
Yt.ts.desc$x
```

## Ploteo de la descomposion

```{r Ploteo de la descomposion}
plot(Yt.ts.desc, xlab = 'Anho')
```

## Resumen de la tendencia

```{r Tendencia}
tendencia <- data.frame(Yt.ts.desc$trend)
tendencia
```
```{r Resumen de tendencia}
summary(tendencia)
```

Remplazar valores nulos por 0
```{r}
tendencia$Yt.ts.desc.trend[is.na(tendencia$Yt.ts.desc.trend)]=0
```

## Modelamiento de la tendencia
```{r}
tendencia$x <- seq(1:nrow(tendencia))
tendencia$x
```

```{r}
modelo <- lm(Yt.ts.desc.trend ~x, data= tendencia)
tendencia_estimada <- modelo$fitted.values
head(tendencia_estimada)
```

## Estacionalidad

```{r}
estacional <- data.frame(Yt.ts.desc$seasonal)
head(estacional)
```

## Estimacion de la serie en base a un modelo multiplicativo

```{r}
dataf <- data.frame(tendencia_estimada,estacional)
colnames(dataf) <- c('tend_est','estacionalidad')

dataf$Yt_est <- dataf$tend_est*dataf$estacionalidad
```

## Grafico del modelo final

```{r}
plot(Yt, col = "red")
points(dataf$Yt_est, type = 'l', col = 'blue' )
```

